### ISSUE TITLE
Additional metrics from /proc/diskstats

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#1119]
Hi,

would you accept a PR so that we have all metrics from /proc/diskstats available even though some of them are not available on Windows / other Unix systems?

What we are interested in is the metrics that /proc/diskstats file displays
 
Each line contains the following 14 fields:
1 - major number
2 - minor number
3 - device name
4 - reads completed successfully
5 - reads merged
6 - sectors read
7 - time spent reading (ms)
8 - writes completed
9 - writes merged
10 - sectors written
11 - time spent writing (ms)
12 - I/Os currently in progress
13 - time spent doing I/Os (ms)
14 - weighted time spent doing I/Os (ms)
 
Kernel 4.18+ appends four more fields for discard tracking putting the total at 18:
15 - discards completed successfully
16 - discards merged
17 - sectors discarded
18 - time spent discarding
 
Kernel 5.5+ appends two more fields for flush requests:
19 - flush requests completed successfully
20 - time spent flushing

**Comment by dbwiddis** [comment]
Sure.  PR away!

**Comment by dbwiddis** [comment]
As an alternative to changing the cross-platform API for this, I'm thinking there's a good middle ground.  I recently finished moving all the Windows WMI calls and performance counter queries into their own "driver" classes under the `oshi.driver.windows` package hierarchy.  Each of these is a publicly accessible util class (all methods are static) to query the underlying information.

 I was envisioning doing similar for Linux calls that read the various `/proc` classes, e.g., create a package `oshi.driver.linux.proc` with a class `DiskStats` that reads these values and matches them up with an `Enum` identifying the column names.

That would leave the API as-is but enable Linux users who wished to query the diskstats values to get them easily.

**Comment by Space2Man** [comment]
Wow, that would be very cool ...

**Comment by dbwiddis** [comment]
Yep. Could do the same thing for the process stats (which would address #535) and network stats (some requested on #696 but there are actually far more available in Linux) and proccess stats (which would address.

Only question is whether to return the data column-based (EnumMap of lists) like the WMI code does, or a List (or Map) of EnumMaps...

**Comment by dbwiddis** [comment]
Take a look at https://github.com/dbwiddis/oshi/commit/b7588b3777ba5e346d05d68089fe3aaa0efbd532 which attempts to implement this.

**Comment by dbwiddis** [comment]
Oops, needed a `trim()` on the line, but it works now.

```
    public static void main(String... args) {
        List<String> ds = FileUtil.readFile(DISK_STATS);
        for (String s : ds) {
            System.out.println(s);
        }
        System.out.println();
        Map<String, Map<IoStat, Long>> stats = getDiskStats();
        for (Entry<String, Map<IoStat, Long>> entry : stats.entrySet()) {
            if (entry.getKey().startsWith("ram") || entry.getKey().startsWith("loop")) {
                continue;
            }
            System.out.println(entry.getKey() + ":");
            Map<IoStat, Long> m = entry.getValue();
            for (IoStat e : IoStat.class.getEnumConstants()) {
                Long val = m.get(e);
                if (val != null) {
                    System.out.println("   " + e.name() + ": " + m.get(e).longValue());
                }
            }
        }
    }
```
Converts this `/proc/diskstats` output:

```
   8       0 sda 60617 2600 1895078 20828 10929 20050 997280 28736 0 7988 49556
   8       1 sda1 60271 2593 1892266 20768 10815 20050 997280 28732 0 7972 49492
   8       2 sda2 2 0 4 0 0 0 0 0 0 0 0
   8       5 sda5 163 7 1360 52 0 0 0 0 0 48 52
```
To an EnumMap:
```
sda5:
   MAJOR: 8
   MINOR: 5
   READS: 163
   READS_MERGED: 7
   READS_SECTOR: 1360
   READS_MS: 52
   WRITES: 0
   WRITES_MERGED: 0
   WRITES_SECTOR: 0
   WRITES_MS: 0
   IO_QUEUE_LENGTH: 0
   IO_MS: 48
   IO_MS_WEIGHTED: 52
sda:
   MAJOR: 8
   MINOR: 0
   READS: 60617
   READS_MERGED: 2600
   READS_SECTOR: 1895078
   READS_MS: 20828
   WRITES: 10929
   WRITES_MERGED: 20050
   WRITES_SECTOR: 997280
   WRITES_MS: 28736
   IO_QUEUE_LENGTH: 0
   IO_MS: 7988
   IO_MS_WEIGHTED: 49556
sda1:
   MAJOR: 8
   MINOR: 1
   READS: 60271
   READS_MERGED: 2593
   READS_SECTOR: 1892266
   READS_MS: 20768
   WRITES: 10815
   WRITES_MERGED: 20050
   WRITES_SECTOR: 997280
   WRITES_MS: 28732
   IO_QUEUE_LENGTH: 0
   IO_MS: 7972
   IO_MS_WEIGHTED: 49492
sda2:
   MAJOR: 8
   MINOR: 2
   READS: 2
   READS_MERGED: 0
   READS_SECTOR: 4
   READS_MS: 0
   WRITES: 0
   WRITES_MERGED: 0
   WRITES_SECTOR: 0
   WRITES_MS: 0
   IO_QUEUE_LENGTH: 0
   IO_MS: 0
   IO_MS_WEIGHTED: 0
```
