### ISSUE TITLE
From version3.x to version 6.x CentralProcesor getProcessorID is different from centralProcessor.getProcessorIdentifier().getProcessorID();

### ISSUE THREAD

**Issue by yzhang921** [oshi/oshi#2130]
From version3.x to version 6.x CentralProcesor getProcessorID is different from centralProcessor.getProcessorIdentifier().getProcessorID(); 

version 3.x: 
```
ProcessorID: 0F81FBFF00500657
manufacturer: OpenStack Foundation
model: OpenStack Nova (version: 13.2.1-20211018165854_809e3c6)
sno: 8e168e10-ca25-4403-a616-7622bbf3dbc5
firmware:
  manufacturer: SeaBIOS
  name: unknown
  description: dmi:bvnSeaBIOS:bvrrel-1.10.2-0-g5f4c7b1-20181220_000000-szxrtosci10000:bd04/01/2014:svnOpenStackFoundation:pnOpenStackNova:pvr13.2.1-20211018165854_809e3c6:cvn:ct1:cvrpc-i440fx-2.8:
  version: rel-1.10.2-0-g5f4c7b1-20181220_000000-szxrtosci10000
  release date: 2014-04-01
```

version 6.x
```
ProcessorID: 57 06 05 00 FF FB 8B 0F
manufacturer: OpenStack Foundation
model: OpenStack Nova (version: 13.2.1-20211018165854_809e3c6)
sno: 8e168e10-ca25-4403-a616-7622bbf3dbc5
firmware:
  manufacturer: unknown
  name: SMBIOS 2.8
  description: dmi:bvnSeaBIOS:bvrrel-1.10.2-0-g5f4c7b1-20181220_000000-szxrtosci10000:bd04/01/2014:svnOpenStackFoundation:pnOpenStackNova:pvr13.2.1-20211018165854_809e3c6:cvn:ct1:cvrpc-i440fx-2.8:
  version: rel-1.10.2-0-g5f4c7b1-20181220_000000-szxrtosci10000
  release date: 2014-04-01
```
