### ISSUE TITLE
Advice on how to get HardwareAbstractionLayer.getDiskStores() working from inside Docker

### ISSUE THREAD

**Issue by Krillsson** [oshi/oshi#2330]
_I recognize that this is not an issue with OSHI. If you don't have the capacity to give me support, feel free to close_ 

I'm working on [sys-API#64](https://github.com/Krillsson/sys-API/issues/64). The issue is that no `DiskStore`s are returned when invoked from Linux inside a docker container. Initially I thought it was related to #1578. I was using the old way of mapping DiskStores with FileSystems (using UUID's).

But then I discovered that running from outside of Docker, the `DiskStore`s are returned as expected. So this is an issue with Docker, and not OSHI or sys-API.

The things I've tried so far are based off of this [stackoverflow article](https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device).

For reference, here is the original [docker-compose.yml](https://github.com/Krillsson/sys-API/blob/master/docker-compose.yml). And here are the additions to it I have tried so far (without success).

```yaml
   # not optimal to run in privileged mode.
   privileged: true
   # https://docs.docker.com/engine/reference/commandline/run/#device-cgroup-rule
   device_cgroup_rules:
     - 'c 8:* rmw'
   volumes:
     # Based off of https://stackoverflow.com/a/62758958
     - /run/udev:/run/udev:ro
     # based on same stackoverflow but blatantly mounting all of /dev inside the container.
     - /dev:/dev
```
