### ISSUE TITLE
Test on macOS M1

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#2470]
While looking into macOS 13 runner capabilities mentioned in https://github.com/oshi/oshi/issues/2428#issuecomment-1672738415 I see that M1 runners are available.  We should add at least one run on this arch.

https://github.com/actions/runner-images/issues/8439

```yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: 'x86_64-apple-darwin'
            os: macos-latest
          - target: 'aarch64-apple-darwin'
            os: macos-latest
```
