### ISSUE TITLE
Returns  'unknown' serial number when running in a docker container, host machine is Mac M2. 

### ISSUE THREAD

**Issue by srpunni** [oshi/oshi#2620]
I am running Java+tomcat REST apis in a docker container, docker container is hosted on Mac M2.
When I run this api server directly on that Mac M2 I get correct serial number, but when I run it inside a docker container on same Mac machine it returns serial number 'unknown'.

Here is my code.

```
import oshi.SystemInfo;
import oshi.hardware.ComputerSystem;
import oshi.hardware.HardwareAbstractionLayer;

public class HardwareUtil {
    public String getSerialNumber() {
        SystemInfo systemInfo = new SystemInfo();
        HardwareAbstractionLayer hardwareAbstractionLayer = systemInfo.getHardware();
        ComputerSystem computerSystem = hardwareAbstractionLayer.getComputerSystem();

        return computerSystem.getSerialNumber();
      
    }
}
```

Dockerfile:
```
FROM tomcat:10-jdk17-openjdk
COPY ./target/abc.war /usr/local/tomcat/webapps/abc.war
CMD ["catalina.sh", "run"]
```
Docker Compose
 ```
 tomcat:
    user: root
    image: image path
    container_name: tomcat
    privileged: true
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
```
