### ISSUE TITLE
Introduce AppVeyor CI

### ISSUE THREAD

**Issue by cilki** [oshi/oshi#881]
Until Travis fully supports Windows, AppVeyor can run Windows builds. I've found it's actually slightly faster than Travis.

Here's the configuration I use which can be adapted to mimic the current `.travis.yml`:
```
version: '{build}'

image: Visual Studio 2017

branches:
  only:
    - master

skip_tags: true

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

init:
  - git config --global --unset core.autocrlf

install:
  - gradlew --version

build_script:
  - gradlew assemble

test_script:
  - gradlew test
```
